FROM node:20-alpine AS builder
WORKDIR /app
COPY kyc-frontend/package*.json ./
RUN npm ci
COPY kyc-frontend ./
RUN npm run build

FROM nginx:alpine AS runtime
COPY --from=builder /app/.next/standalone /usr/share/nginx/html
COPY --from=builder /app/.next/static /usr/share/nginx/html/.next/static
COPY kyc/infrastructure/docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]